# Generated by Django 5.2.2 on 2025-09-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldDisplayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('model_label', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='BlockColumnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('fields', models.JSONField(default=list)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bi.block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'user', 'name'), name='unique_column_config_per_user_block')],
            },
        ),
        migrations.CreateModel(
            name='BlockFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('values', models.JSONField(default=dict)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bi.block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'user', 'name'), name='unique_filter_config_per_user_block')],
            },
        ),
        migrations.CreateModel(
            name='ColumnConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('fields', models.JSONField(default=list)),
                ('site_key', models.CharField(blank=True, max_length=64, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bi.block')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'name', 'site_key'), name='unique_column_template_per_block_site')],
            },
        ),
        migrations.CreateModel(
            name='FilterConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('values', models.JSONField(default=dict)),
                ('site_key', models.CharField(blank=True, max_length=64, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bi.block')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'name', 'site_key'), name='unique_filter_template_per_block_site')],
            },
        ),
        migrations.CreateModel(
            name='PivotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('schema', models.JSONField(default=dict)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bi.block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'user', 'name'), name='unique_pivot_config_per_user_block')],
            },
        ),
        migrations.CreateModel(
            name='PivotConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('schema', models.JSONField(default=dict)),
                ('site_key', models.CharField(blank=True, max_length=64, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bi.block')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'name', 'site_key'), name='unique_pivot_template_per_block_site')],
            },
        ),
        migrations.CreateModel(
            name='RepeaterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('schema', models.JSONField(default=dict)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bi.block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'user', 'name'), name='unique_repeater_config_per_user_block')],
            },
        ),
        migrations.CreateModel(
            name='RepeaterConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('schema', models.JSONField(default=dict)),
                ('site_key', models.CharField(blank=True, max_length=64, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bi.block')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'name', 'site_key'), name='unique_repeater_template_per_block_site')],
            },
        ),
    ]
