# Generated by Django 5.2.2 on 2025-09-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bi', '0004_rename_filterlayouttemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockfilterlayouttemplate',
            options={'verbose_name': 'Block Filter Layout Template', 'verbose_name_plural': 'Block Filter Layout Templates'},
        ),
    ]
