# Generated by Django 5.2.2 on 2025-10-20 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('django_bi', '0008_add_spacer_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('w', models.PositiveIntegerField(default=4)),
                ('h', models.PositiveIntegerField(default=2)),
                ('col_span', models.PositiveIntegerField(default=1)),
                ('row_span', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('preferred_filter_name', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_column_config_name', models.CharField(blank=True, default='', max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bi.block')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='django_bi.layout')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LayoutFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('values', models.JSONField(default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=7)),
                ('is_default', models.BooleanField(default=False)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_configs', to='django_bi.layout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='layout',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_layout_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='layout',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_layout_slug_per_user'),
        ),
        migrations.AddIndex(
            model_name='layoutblock',
            index=models.Index(fields=['layout', 'position'], name='layout_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('w__gte', 1), ('w__lte', 12)), name='layoutblock_w_range'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('h__gte', 1), ('h__lte', 12)), name='layoutblock_h_range'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('x__gte', 0)), name='layoutblock_x_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('y__gte', 0)), name='layoutblock_y_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='layoutfilterconfig',
            constraint=models.UniqueConstraint(fields=('layout', 'user', 'name'), name='unique_layout_filter_per_user'),
        ),
        migrations.AddConstraint(
            model_name='layoutfilterconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('layout', 'user'), name='unique_default_layout_filter_per_user'),
        ),
    ]
