# Generated by Django 5.2.2 on 2025-09-19 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterLayoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=dict)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block', unique=True)),
            ],
            options={
                'verbose_name': 'Filter Layout Template',
                'verbose_name_plural': 'Filter Layout Templates',
            },
        ),
    ]
