# Generated by Django 5.2.2 on 2025-08-05 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='blockcolumnconfig',
            constraint=models.UniqueConstraint(fields=('block', 'user', 'name'), name='unique_column_config_per_user_block'),
        ),
    ]
