# Generated by Django 5.2.2 on 2025-08-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_blockcolumnconfig_unique_column_config_per_user_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDisplayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('model_label', 'field_name')},
            },
        ),
    ]
