# Generated by Django 5.2.2 on 2025-08-08 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0003_fielddisplayrule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="blockfilterconfig",
            constraint=models.UniqueConstraint(
                fields=("block", "user", "name"),
                name="unique_filter_config_per_user_block",
            ),
        ),
    ]

