# Generated by Django 5.2.2 on 2025-09-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_alter_blockfilterlayouttemplate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pivotconfigtemplate',
            name='block',
        ),
        migrations.AddField(
            model_name='blockcolumnconfig',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=7),
        ),
        migrations.AddField(
            model_name='pivotconfig',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=7),
        ),
        migrations.DeleteModel(
            name='ColumnConfigTemplate',
        ),
        migrations.DeleteModel(
            name='PivotConfigTemplate',
        ),
    ]
