# Generated by Django 5.2.2 on 2025-09-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_remove_pivotconfigtemplate_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockfilterconfig',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=7),
        ),
        migrations.DeleteModel(
            name='FilterConfigTemplate',
        ),
    ]
