# Generated by Django 5.2.2 on 2025-09-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_pivotconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PivotConfig',
        ),
    ]
