# Generated by Django 5.2.2 on 2025-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_add_spacer_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='block',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='block',
            name='override_display',
            field=models.BooleanField(default=True),
        ),
    ]
