# Generated by Django 5.2.2 on 2025-09-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_pivotconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pivotconfig',
            name='source_model',
        ),
    ]

