# Generated by Django 5.2.2 on 2025-09-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_remove_blocktableconfig_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
