# Generated by Django 5.2.2 on 2025-09-07 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_repeaterconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('fields', models.JSONField(default=list)),
                ('site_key', models.CharField(blank=True, max_length=64, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'name', 'site_key'), name='unique_column_template_per_block_site')],
            },
        ),
        migrations.CreateModel(
            name='PivotConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('schema', models.JSONField(default=dict)),
                ('site_key', models.CharField(blank=True, max_length=64, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'name', 'site_key'), name='unique_pivot_template_per_block_site')],
            },
        ),
        migrations.CreateModel(
            name='RepeaterConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('schema', models.JSONField(default=dict)),
                ('site_key', models.CharField(blank=True, max_length=64, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'name', 'site_key'), name='unique_repeater_template_per_block_site')],
            },
        ),
    ]
