# Generated by Django 5.2.2 on 2025-09-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0012_columnconfigtemplate_pivotconfigtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255)),
                ('is_default', models.BooleanField(default=True)),
                ('values', models.JSONField(default=dict)),
                ('site_key', models.CharField(blank=True, max_length=64, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'name', 'site_key'), name='unique_filter_template_per_block_site')],
            },
        ),
    ]
