# Generated by Django 5.2.2 on 2025-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0012_alter_block_category_alter_block_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='enabled',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='override_display',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
