# Generated by Django 5.2.2 on 2025-10-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0013_alter_block_enabled_alter_block_override_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeaterconfigtemplate',
            name='block',
        ),
        migrations.DeleteModel(
            name='RepeaterConfig',
        ),
        migrations.DeleteModel(
            name='RepeaterConfigTemplate',
        ),
    ]
