# Generated by Django 5.2.7 on 2025-10-20 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0014_remove_repeaterconfigtemplate_block_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=7,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether this layout should be the default for the owner.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("owner", "name"),
            },
        ),
        migrations.CreateModel(
            name="LayoutBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for the block within the layout.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom title displayed for this block instance.",
                        max_length=255,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Block-specific configuration payload.",
                    ),
                ),
                (
                    "row_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Zero-based row index for grid placement."
                    ),
                ),
                (
                    "column_index",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Zero-based column index for grid placement.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordering value applied when rendering blocks in sequence.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_blocks",
                        to="blocks.block",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_blocks",
                        to="blocks.layout",
                    ),
                ),
            ],
            options={
                "ordering": ("layout", "order", "row_index", "column_index", "slug"),
            },
        ),
        migrations.CreateModel(
            name="LayoutFilterConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=7,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("values", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_configs",
                        to="blocks.layout",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_filter_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("layout", "owner", "name"),
            },
        ),
        migrations.AddIndex(
            model_name="layout",
            index=models.Index(fields=["owner", "slug"], name="layout_owner_slug_idx"),
        ),
        migrations.AddConstraint(
            model_name="layout",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"), name="unique_layout_owner_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="layoutblock",
            index=models.Index(
                fields=["layout", "order"], name="layout_block_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutblock",
            constraint=models.UniqueConstraint(
                fields=("layout", "slug"), name="unique_layout_block_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutfilterconfig",
            constraint=models.UniqueConstraint(
                fields=("layout", "slug"), name="unique_layout_filter_config_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutfilterconfig",
            constraint=models.UniqueConstraint(
                fields=("layout", "owner", "name"),
                name="unique_layout_filter_config_name_per_owner",
            ),
        ),
    ]
