# Generated by Django 5.2.2 on 2025-07-07 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('workflow', '0005_alter_state_allowed_groups_alter_state_is_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('late', 'Late'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='common.productionorderoperation')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
