# Generated by Django 5.2.2 on 2025-09-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('django_bi', '0011_workflow_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='common.calendar'),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='calendarshift',
            name='calendar_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='common.calendarday'),
        ),
        migrations.AddField(
            model_name='calendarshift',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='calendarshift',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fx_base_rates', to='common.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fx_quote_rates', to='common.currency'),
        ),
        migrations.AddField(
            model_name='item',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='item',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.itemgroup', verbose_name='Item Group'),
        ),
        migrations.AddConstraint(
            model_name='itemgrouptype',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_item_group_type'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.itemgrouptype', verbose_name='Item Group Type'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_item_type'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.itemtype', verbose_name='Item Type'),
        ),
        migrations.AddField(
            model_name='labor',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.calendar'),
        ),
        migrations.AddField(
            model_name='labor',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='labor',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='calendarshift',
            name='labours',
            field=models.ManyToManyField(blank=True, related_name='assigned_shifts', to='common.labor'),
        ),
        migrations.AddField(
            model_name='laborvacation',
            name='labor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacations', to='common.labor'),
        ),
        migrations.AddField(
            model_name='laborvacation',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='laborvacation',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='machine',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.calendar'),
        ),
        migrations.AddField(
            model_name='machine',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='machine',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='machinedowntime',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.machine'),
        ),
        migrations.AddField(
            model_name='machinedowntime',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='machinedowntime',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='plannedproductionorder',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannedproductionorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item'),
        ),
        migrations.AddField(
            model_name='plannedproductionorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner'),
        ),
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item'),
        ),
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner'),
        ),
        migrations.AddField(
            model_name='productionmrpmessage',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='common.mrprescheduledaysclassification'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='productionmrpmessage',
            name='production_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_message', to='common.productionorder'),
        ),
        migrations.AddField(
            model_name='productionordercategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.productionordercategory'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.productionordercategory'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.machine'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.productionorder'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='productionorderschedule',
            name='labor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.labor'),
        ),
        migrations.AddField(
            model_name='productionorderschedule',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.machine'),
        ),
        migrations.AddField(
            model_name='productionorderschedule',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='common.productionorderoperation'),
        ),
        migrations.AddField(
            model_name='productionorderschedule',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='productionorderschedule',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_program_code'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='purchasemrpmessage',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='common.mrprescheduledaysclassification'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='purchaseordercategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.purchaseordercategory'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.purchaseordercategory'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='purchasemrpmessage',
            name='pol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_message', to='common.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='op_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.purchaseorderline'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('number',), name='unique_receipt'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='common.purchasetimelinessclassification'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='common.purchaseorderline', verbose_name='PO Line (Obj)'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='common.receipt'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='salesordercategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.salesordercategory'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.salesordercategory'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.salesorder'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='calendarshift',
            name='shift_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.shifttemplate'),
        ),
        migrations.AddField(
            model_name='sovalidateaggregate',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_validate_company_rows', to='common.businesspartner'),
        ),
        migrations.AddField(
            model_name='sovalidateaggregate',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_validate_customer_rows', to='common.businesspartner'),
        ),
        migrations.AddField(
            model_name='sovalidateaggregate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_validate_aggregates', to='common.item'),
        ),
        migrations.AddField(
            model_name='task',
            name='alternate_machines',
            field=models.ManyToManyField(blank=True, help_text='Other machines that can perform this task', null=True, related_name='alternate_for_tasks', to='common.machine'),
        ),
        migrations.AddField(
            model_name='task',
            name='primary_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_tasks', to='common.machine'),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.task'),
        ),
        migrations.AddField(
            model_name='todo',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='common.todo'),
        ),
        migrations.AddField(
            model_name='uom',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='uom',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.uom'),
        ),
        migrations.AddField(
            model_name='plannedpurchaseorder',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.uom'),
        ),
        migrations.AddField(
            model_name='plannedproductionorder',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.uom'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.workflow'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_bi.state'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='workcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.workcenter'),
        ),
        migrations.AddField(
            model_name='labor',
            name='workcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.workcenter'),
        ),
        migrations.AddConstraint(
            model_name='businesspartner',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_business_partner'),
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_calendar_name'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base', 'quote', 'rate_date'], name='idx_rate_pair_date'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base', 'quote', 'rate_date'), name='unique_exchange_rate'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_item'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_machine'),
        ),
        migrations.AddConstraint(
            model_name='productionordercategory',
            constraint=models.UniqueConstraint(fields=('code', 'parent'), name='unique_production_order_category'),
        ),
        migrations.AddConstraint(
            model_name='productionordercategory',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent')), _negated=True), name='productionordercategory_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('production_order',), name='unique_production_order'),
        ),
        migrations.AddConstraint(
            model_name='itemgroup',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_item_group'),
        ),
        migrations.AddConstraint(
            model_name='purchaseordercategory',
            constraint=models.UniqueConstraint(fields=('code', 'parent'), name='unique_purchase_order_category'),
        ),
        migrations.AddConstraint(
            model_name='purchaseordercategory',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent')), _negated=True), name='purchaseordercategory_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_purchase_order'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'line'), name='unique_receipt_line'),
        ),
        migrations.AddConstraint(
            model_name='salesordercategory',
            constraint=models.UniqueConstraint(fields=('code', 'parent'), name='unique_sales_order_category'),
        ),
        migrations.AddConstraint(
            model_name='salesordercategory',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent')), _negated=True), name='salesordercategory_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_sales_order'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('order', 'line', 'sequence'), name='unique_sales_order_line_sequence'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_shift_template_name'),
        ),
        migrations.AddIndex(
            model_name='sovalidateaggregate',
            index=models.Index(fields=['period'], name='common_sova_period_14fe9b_idx'),
        ),
        migrations.AddIndex(
            model_name='sovalidateaggregate',
            index=models.Index(fields=['customer', 'period'], name='common_sova_custome_2bf57f_idx'),
        ),
        migrations.AddIndex(
            model_name='sovalidateaggregate',
            index=models.Index(fields=['company', 'period'], name='common_sova_company_82c072_idx'),
        ),
        migrations.AddIndex(
            model_name='sovalidateaggregate',
            index=models.Index(fields=['item', 'period'], name='common_sova_item_id_17a1e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sovalidateaggregate',
            unique_together={('item', 'company', 'customer', 'period')},
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_task'),
        ),
        migrations.AddConstraint(
            model_name='uom',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_uom_code'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'line', 'sequence'), name='unique_purchase_order_line'),
        ),
        migrations.AddConstraint(
            model_name='plannedpurchaseorder',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_planned_purchase_order'),
        ),
        migrations.AddConstraint(
            model_name='plannedproductionorder',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_planned_production_order'),
        ),
        migrations.AddConstraint(
            model_name='workcenter',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_work_center'),
        ),
        migrations.AddConstraint(
            model_name='productionorderoperation',
            constraint=models.UniqueConstraint(fields=('production_order', 'operation'), name='unique_production_order_operation'),
        ),
        migrations.AddConstraint(
            model_name='labor',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_labor_code'),
        ),
    ]
