# Generated by Django 5.2.2 on 2025-07-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_productionorderschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='sort_id',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='holidays',
            field=models.JSONField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='working_days',
            field=models.JSONField(blank=True, default=True),
        ),
    ]
