# Generated by Django 5.2.2 on 2025-09-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmrpmessage',
            name='mrp_message',
            field=models.TextField(blank=True, default='', null=True, verbose_name='MRP Message'),
        ),
        migrations.AlterField(
            model_name='purchasemrpmessage',
            name='mrp_message',
            field=models.TextField(blank=True, default='', null=True, verbose_name='MRP Message'),
        ),
    ]
