# Generated by Django 5.2.2 on 2025-07-08 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_productionorder_sort_id_and_more'),
        ('workflow', '0005_alter_state_allowed_groups_alter_state_is_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='holidays',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='working_days',
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='labor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.labor'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='required_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='required_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='total_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.machine'),
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_working_day', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='common.calendar')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='common.calendarday')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.shifttemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
