# Generated by Django 5.2.2 on 2025-07-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_calendar_holidays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorderschedule',
            name='status',
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='priority',
            field=models.PositiveIntegerField(default=999, help_text='Lower numbers = higher priority. 1 = top priority'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='remaining_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productionorderschedule',
            name='execution_state',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('late', 'Late')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='productionorderschedule',
            name='schedule_state',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('scheduled', 'Scheduled')], default='unscheduled', max_length=20),
        ),
    ]
