# Generated by Django 5.2.2 on 2025-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_productionorderschedule_status_and_more'),
        ('workflow', '0005_alter_state_allowed_groups_alter_state_is_end_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workcenter',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_work_center'),
        ),
    ]
