# Generated by Django 5.2.2 on 2025-09-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_update_roadmap_app_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
