# Generated by Django 5.2.2 on 2025-07-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_labor_unique_labor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.calendar'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='workcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.workcenter'),
        ),
    ]
