# Generated by Django 5.2.2 on 2025-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_labor_calendar_alter_labor_workcenter'),
        ('workflow', '0005_alter_state_allowed_groups_alter_state_is_end_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_calendar_name'),
        ),
    ]
