# Generated by Django 5.2.2 on 2025-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_shifttemplate_unique_shift_template_name'),
        ('workflow', '0005_alter_state_allowed_groups_alter_state_is_end_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='code',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_item_code'),
        ),
    ]
