# Generated by Django 5.2.2 on 2025-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_item_unique_item_code_item_unique_item'),
        ('workflow', '0005_alter_state_allowed_groups_alter_state_is_end_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_machine'),
        ),
    ]
