# Generated by Django 5.2.2 on 2025-07-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_machine_unique_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='priority',
        ),
    ]
