# Generated by Django 5.2.2 on 2025-07-09 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remove_productionorder_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorderoperation',
            name='operation',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.productionorder'),
        ),
    ]
