# Generated by Django 5.2.2 on 2025-07-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_productionorderoperation_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorderoperation',
            name='operation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='required_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='required_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
