# Generated by Django 5.2.2 on 2025-07-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_productionorderoperation_operation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionorderoperation',
            old_name='required_end_date',
            new_name='required_end',
        ),
        migrations.RenameField(
            model_name='productionorderoperation',
            old_name='required_start_date',
            new_name='required_start',
        ),
    ]
