# Generated by Django 5.2.2 on 2025-07-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_purchaseorder_purchaseorderline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='final_receive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
