# Generated by Django 5.2.2 on 2025-07-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_alter_purchaseorderline_final_receive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderoperation',
            name='op_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.purchaseorderline'),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='labor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.labor'),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.machine'),
        ),
    ]
