# Generated by Django 5.2.2 on 2025-07-15 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_productionorderoperation_op_po_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorderoperation',
            name='labor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.labor'),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.machine'),
        ),
    ]
