# Generated by Django 5.2.2 on 2025-07-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_machinedowntime'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderoperation',
            name='alternate_machines',
            field=models.ManyToManyField(blank=True, help_text='Other machines this op can run on', related_name='alternate_for_operations', to='common.machine'),
        ),
    ]
