# Generated by Django 5.2.2 on 2025-07-15 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_productionorderoperation_alternate_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderschedule',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.machine'),
        ),
    ]
