# Generated by Django 5.2.2 on 2025-07-15 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_productionorderschedule_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorderschedule',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='common.productionorderoperation'),
        ),
    ]
