# Generated by Django 5.2.2 on 2025-07-15 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_alter_productionorderschedule_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorderoperation',
            name='alternate_machines',
        ),
        migrations.RemoveField(
            model_name='productionorderoperation',
            name='machine',
        ),
        migrations.AddField(
            model_name='task',
            name='alternate_machines',
            field=models.ManyToManyField(blank=True, help_text='Other machines that can perform this task', null=True, related_name='alternate_for_tasks', to='common.machine'),
        ),
        migrations.AddField(
            model_name='task',
            name='primary_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_tasks', to='common.machine'),
        ),
    ]
