# Generated by Django 5.2.2 on 2025-07-15 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_remove_productionorderoperation_alternate_machines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderoperation',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.machine'),
        ),
    ]
