# Generated by Django 5.2.2 on 2025-07-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_productionorderoperation_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorderoperation',
            name='labor',
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='workcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='common.workcenter'),
        ),
    ]
