# Generated by Django 5.2.2 on 2025-07-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_remove_productionorderoperation_labor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderschedule',
            name='labor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.labor'),
        ),
    ]
