# Generated by Django 5.2.2 on 2025-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_laborvacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborvacation',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='laborvacation',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
