# Generated by Django 5.2.2 on 2025-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_alter_laborvacation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
