# Generated by Django 5.2.2 on 2025-07-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_labor_code'),
        ('workflow', '0005_alter_state_allowed_groups_alter_state_is_end_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='labor',
            name='unique_labor_name',
        ),
        migrations.AddConstraint(
            model_name='labor',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_labor_code'),
        ),
    ]
