# Generated by Django 5.2.2 on 2025-08-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_calendarshift_labours'),
        ('workflow', '0005_alter_state_allowed_groups_alter_state_is_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='state',
        ),
        migrations.RemoveField(
            model_name='calendarday',
            name='state',
        ),
        migrations.RemoveField(
            model_name='calendarshift',
            name='state',
        ),
        migrations.RemoveField(
            model_name='item',
            name='state',
        ),
        migrations.RemoveField(
            model_name='labor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='laborvacation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='state',
        ),
        migrations.RemoveField(
            model_name='machinedowntime',
            name='state',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='state',
        ),
        migrations.RemoveField(
            model_name='productionorderoperation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='productionorderschedule',
            name='state',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='state',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shifttemplate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='state',
        ),
        migrations.AddField(
            model_name='calendar',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='calendarshift',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='item',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='labor',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='laborvacation',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='machine',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='machinedowntime',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='productionorderschedule',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='calendarday',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='calendarshift',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='item',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='laborvacation',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='machinedowntime',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='productionorderschedule',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='workflow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
    ]
