# Generated by Django 5.2.2 on 2025-08-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_remove_calendar_state_remove_calendarday_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='part_no',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
