# Generated by Django 5.2.2 on 2025-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_remove_productionorder_part_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDisplayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('model_label', 'field_name')},
            },
        ),
    ]
