# Generated by Django 5.2.2 on 2025-08-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_fielddisplayrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='production_order',
            field=models.CharField(max_length=10, verbose_name='Prod Order'),
        ),
    ]
