# Generated by Django 5.2.2 on 2025-08-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_alter_productionorder_production_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldDisplayRule',
        ),
    ]
