# Generated by Django 5.2.2 on 2025-08-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_delete_fielddisplayrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='workflow_state',
        ),
    ]
