# Generated by Django 5.2.2 on 2025-08-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_remove_productionorder_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item'),
        ),
    ]
