# Generated by Django 5.2.2 on 2025-08-22 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_productionorder_item'),
        ('workflow', '0006_remove_state_allowed_groups_transitionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='calendarday',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='calendarday',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='calendarshift',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='calendarshift',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='item',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='item',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='laborvacation',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='laborvacation',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='machinedowntime',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='machinedowntime',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='productionorderoperation',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='productionorderschedule',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='productionorderschedule',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='task',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
    ]
