# Generated by Django 5.2.2 on 2025-09-02 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_productionorder_workflow_and_more'),
        ('workflow', '0006_remove_state_allowed_groups_transitionlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=15)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('-', '-'), ('active', 'Active'), ('inactive', 'Inactive')], default='-', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_business_partner')],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner')),
                ('workflow', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow')),
                ('workflow_state', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order',), name='unique_sales_order')],
            },
        ),
    ]
