# Generated by Django 5.2.2 on 2025-09-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_businesspartner_salesorder'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner'),
        ),
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_ct', models.ForeignKey(help_text='Pick the model this refers to.', limit_choices_to=models.Q(('app_label__in', ['common'])), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Model')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.ordercategory')),
            ],
        ),
        migrations.AddField(
            model_name='salesorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.ordercategory'),
        ),
        migrations.AddConstraint(
            model_name='ordercategory',
            constraint=models.UniqueConstraint(fields=('code', 'model_ct', 'parent'), name='unique_category'),
        ),
        migrations.AddConstraint(
            model_name='ordercategory',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent')), _negated=True), name='ordercategory_no_self_parent'),
        ),
    ]
