# Generated by Django 5.2.2 on 2025-09-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_alter_salesorder_customer_ordercategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=5)),
                ('quote_currency', models.CharField(max_length=5)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_line', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('d1_date', models.DateField(blank=True, null=True)),
                ('d2_date', models.DateField(blank=True, null=True)),
                ('d3_date', models.DateField(blank=True, null=True)),
                ('d4_date', models.DateField(blank=True, null=True)),
                ('total_quantity', models.FloatField(blank=True, null=True)),
                ('delivered_quantity', models.FloatField(blank=True, null=True)),
                ('back_order', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('customer_po', models.CharField(blank=True, default='', max_length=20)),
                ('customer_po_line', models.CharField(blank=True, default='', max_length=20)),
                ('total_amount_cad', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.salesorder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sales_order', 'sales_order_line', 'sequence'), name='unique_sales_order_line_sequence')],
            },
        ),
    ]
