# Generated by Django 5.2.2 on 2025-09-02 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_currency_salesorderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_purchase_order', models.CharField(blank=True, default='', max_length=30)),
                ('customer', models.CharField(blank=True, default='', max_length=30)),
                ('d2_date', models.DateField(blank=True, null=True)),
                ('back_order', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item')),
            ],
        ),
    ]
