# Generated by Django 5.2.2 on 2025-09-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_customerpurchaseorder'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerpurchaseorder',
            constraint=models.UniqueConstraint(fields=('customer_purchase_order',), name='unique_customer_purchase_order'),
        ),
    ]
