# Generated by Django 5.2.2 on 2025-09-05 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_businesspartner_parent'),
        ('workflow', '0006_remove_state_allowed_groups_transitionlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='salesorderline',
            name='unique_sales_order_line_sequence',
        ),
        migrations.RenameField(
            model_name='salesorderline',
            old_name='sales_order_line',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='salesorderline',
            old_name='sales_order',
            new_name='order',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.ordercategory'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='amount_home_currency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='amount_original_currency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='back_order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='initial_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='modified_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='received_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='supplier_confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='total_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('order', 'line', 'sequence'), name='unique_sales_order_line_sequence'),
        ),
        migrations.AddField(
            model_name='uom',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='uom',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.uom'),
        ),
        migrations.AddConstraint(
            model_name='uom',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_uom_code'),
        ),
    ]
