# Generated by Django 5.2.2 on 2025-09-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0047_customerpurchaseorder_unique_customer_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoValidateAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('Collins', 'Collins'), ('MAI', 'MAI')], max_length=32)),
                ('period', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_validate_aggregates', to='common.item')),
            ],
            options={
                'verbose_name': 'SO Validator Aggregate',
                'verbose_name_plural': 'SO Validator Aggregates',
                'indexes': [models.Index(fields=['period'], name='common_sova_period_14fe9b_idx'), models.Index(fields=['company', 'period'], name='common_sova_company_7bb38f_idx'), models.Index(fields=['item', 'period'], name='common_sova_item_id_17a1e8_idx')],
                'unique_together': {('item', 'company', 'period')},
            },
        ),
    ]
