# Generated by Django 5.2.2 on 2025-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0047_uom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='final_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
