# Generated by Django 5.2.2 on 2025-09-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_alter_purchaseorderline_final_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
