# Generated by Django 5.2.2 on 2025-09-02 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_sovalidateaggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.businesspartner'),
        ),
    ]
