# Generated by Django 5.2.2 on 2025-09-02 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0049_businesspartner_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchaseorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner'),
        ),
    ]
