# Generated by Django 5.2.2 on 2025-09-02 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0050_alter_customerpurchaseorder_customer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sovalidateaggregate',
            new_name='common_sova_company_82c072_idx',
            old_name='common_sova_company_7bb38f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sovalidateaggregate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sovalidateaggregate',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_validate_customer_rows', to='common.businesspartner'),
        ),
        migrations.AlterField(
            model_name='sovalidateaggregate',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_validate_company_rows', to='common.businesspartner'),
        ),
        migrations.AlterUniqueTogether(
            name='sovalidateaggregate',
            unique_together={('item', 'company', 'customer', 'period')},
        ),
        migrations.AddIndex(
            model_name='sovalidateaggregate',
            index=models.Index(fields=['customer', 'period'], name='common_sova_custome_2bf57f_idx'),
        ),
    ]
