# Generated by Django 5.2.2 on 2025-09-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0050_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(db_index=True, default=999),
        ),
    ]
