# Generated by Django 5.2.2 on 2025-09-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_alter_todo_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('fiscal_year_start_day', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otd_target_percent', models.PositiveIntegerField(default=95, help_text='Target OTD percentage')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTimelinessClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower runs first')),
                ('active', models.BooleanField(default=True)),
                ('min_days', models.IntegerField(blank=True, null=True)),
                ('min_inclusive', models.BooleanField(default=True)),
                ('max_days', models.IntegerField(blank=True, null=True)),
                ('max_inclusive', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.PositiveIntegerField()),
                ('received_quantity', models.FloatField(blank=True, null=True)),
                ('receipt_date', models.DateField(blank=True, db_index=True, null=True)),
                ('days_offset', models.IntegerField(blank=True, null=True)),
                ('amount_home_currency', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='common.purchasetimelinessclassification')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='common.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='common.receipt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('receipt', 'line'), name='unique_receipt_line')],
            },
        ),
    ]
