# Generated by Django 5.2.2 on 2025-09-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_rename_common_sova_company_7bb38f_idx_common_sova_company_82c072_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sovalidateaggregate',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_validate_company_rows', to='common.businesspartner'),
        ),
    ]
