# Generated by Django 5.2.2 on 2025-09-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_globalsettings_purchasesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetimelinessclassification',
            name='counts_for_ontime',
            field=models.BooleanField(default=False, help_text='If true, rows with this class count toward OTD%'),
        ),
    ]
