# Generated by Django 5.2.2 on 2025-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_purchasetimelinessclassification_counts_for_ontime'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('number',), name='unique_receipt'),
        ),
    ]
