# Generated by Django 5.2.2 on 2025-09-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_receipt_unique_receipt'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('mrp_message', models.TextField(blank=True, default='')),
                ('mrp_reschedule_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reschedule_delta_days', models.IntegerField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(blank=True, choices=[('PULL_IN', 'Pull In'), ('PUSH_OUT', 'Push Out')], db_index=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label': 'common', 'model__in': ['purchaseorderline', 'productionorder']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='mrp_msg_target_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlannedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('type', models.CharField(choices=[('PPUR', 'Planned Purchase Order'), ('PPRO', 'Planned Production Order')], max_length=4)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.uom')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'type'), name='unique_planned_order_per_type')],
            },
        ),
    ]
