# Generated by Django 5.2.2 on 2025-09-09 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_plannedorder_buyer_plannedorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='type',
            field=models.CharField(blank=True, choices=[('PPUR', 'Planned Purchase Order'), ('PPRO', 'Planned Production Order')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.uom'),
        ),
    ]
