# Generated by Django 5.2.2 on 2025-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_alter_plannedorder_item_alter_plannedorder_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedorder',
            name='order',
            field=models.CharField(max_length=20, verbose_name='Order'),
        ),
    ]
