# Generated by Django 5.2.2 on 2025-09-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_mrpmessage_typed_relations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mrpmessage',
            name='mrp_msg_target_idx',
        ),
    ]
