# Generated by Django 5.2.2 on 2025-09-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0060_remove_mrpmessage_mrp_msg_target_idx'),
        ('common', '0061_purchaseorderline_status'),
    ]

    operations = [
    ]
