# Generated by Django 5.2.2 on 2025-09-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0062_merge_20250910_1219"),
    ]

    operations = [
        migrations.CreateModel(
            name="MrpRescheduleDaysClassification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("min_days", models.IntegerField(blank=True, null=True)),
                ("max_days", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("min_days", "id"),
            },
        ),
        migrations.AddField(
            model_name="mrpmessage",
            name="classification",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]

