# Generated by Django 5.2.2 on 2025-09-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0064_mrpmessage_classification_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptline',
            name='line',
            field=models.PositiveIntegerField(verbose_name='Receipt Line'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='common.purchaseorderline', verbose_name='PO Line (Obj)'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='common.receipt', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='receipt_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Receipt Date'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='received_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Received Quantity'),
        ),
    ]
