# Generated by Django 5.2.2 on 2025-09-11 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0065_alter_receiptline_line_alter_receiptline_po_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='code',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Business Partner Code'),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Business Partner Name'),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.businesspartner', verbose_name='Parent Business Partner'),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('active', 'Active'), ('inactive', 'Inactive')], default='-', max_length=10, verbose_name='Business Partner Status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='mrpmessage',
            name='direction',
            field=models.CharField(blank=True, choices=[('PULL_IN', 'Pull In'), ('PUSH_OUT', 'Push Out')], db_index=True, max_length=8, null=True, verbose_name='Reschedule Direction'),
        ),
        migrations.AlterField(
            model_name='mrpmessage',
            name='mrp_message',
            field=models.TextField(blank=True, default='', verbose_name='MRP Message'),
        ),
        migrations.AlterField(
            model_name='mrpmessage',
            name='mrp_reschedule_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='MRP Reschedule Date'),
        ),
        migrations.AlterField(
            model_name='mrpmessage',
            name='reschedule_delta_days',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Reschedule Delta Days'),
        ),
        migrations.AlterField(
            model_name='mrprescheduledaysclassification',
            name='max_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Days'),
        ),
        migrations.AlterField(
            model_name='mrprescheduledaysclassification',
            name='min_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Days'),
        ),
        migrations.AlterField(
            model_name='mrprescheduledaysclassification',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='MRP Reschedule Days Classification Name'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='order',
            field=models.CharField(max_length=20, verbose_name='Planned Order'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned End Date'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned Start Date'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Planned Quantity'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='required_date',
            field=models.DateField(blank=True, null=True, verbose_name='Required Date'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='type',
            field=models.CharField(blank=True, choices=[('PPUR', 'Planned Purchase Order'), ('PPRO', 'Planned Production Order')], max_length=4, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order',
            field=models.CharField(max_length=10, verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='amount_home_currency',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount (Home Curr.)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='amount_original_currency',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount (Orig. Curr.)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='back_order',
            field=models.FloatField(blank=True, null=True, verbose_name='Back Order'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='comments',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='final_receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Report Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='initial_receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Initial Receive Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='line',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PO Line'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='modified_receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Modified Receive Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='received_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Received Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10, verbose_name='Purchase Order Line Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='supplier_confirmed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Supplier Confirmed Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='total_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchasetimelinessclassification',
            name='counts_for_ontime',
            field=models.BooleanField(default=False, help_text='If true, rows with this class count toward OTD%', verbose_name='Counts for OTD%'),
        ),
        migrations.AlterField(
            model_name='purchasetimelinessclassification',
            name='max_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Days Offset'),
        ),
        migrations.AlterField(
            model_name='purchasetimelinessclassification',
            name='max_inclusive',
            field=models.BooleanField(default=True, verbose_name='Max Inclusive'),
        ),
        migrations.AlterField(
            model_name='purchasetimelinessclassification',
            name='min_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Days Offset'),
        ),
        migrations.AlterField(
            model_name='purchasetimelinessclassification',
            name='min_inclusive',
            field=models.BooleanField(default=True, verbose_name='Min Inclusive'),
        ),
        migrations.AlterField(
            model_name='purchasetimelinessclassification',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Supplier OTD Classification Name'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Receipt Number'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='common.receipt'),
        ),
    ]
