# Generated by Django 5.2.2 on 2025-09-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_alter_businesspartner_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='home_currency_code',
            field=models.CharField(default='CAD', max_length=5),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_code', models.CharField(db_index=True, max_length=5)),
                ('quote_code', models.CharField(db_index=True, max_length=5)),
                ('rate_date', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['base_code', 'quote_code', 'rate_date'], name='idx_rate_pair_date')],
                'constraints': [models.UniqueConstraint(fields=('base_code', 'quote_code', 'rate_date'), name='unique_exchange_rate')],
            },
        ),
    ]
