# Generated by Django 5.2.2 on 2025-09-13 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0067_globalsettings_home_currency_code_exchangerate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangerate',
            name='unique_exchange_rate',
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='idx_rate_pair_date',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='price',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='quote_currency',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='base_code',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='quote_code',
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fx_base_rates', to='common.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fx_quote_rates', to='common.currency'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base', 'quote', 'rate_date'], name='idx_rate_pair_date'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base', 'quote', 'rate_date'), name='unique_exchange_rate'),
        ),
    ]
