# Generated by Django 5.2.2 on 2025-09-14 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0068_remove_exchangerate_unique_exchange_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercategory',
            name='model_ct',
        ),
        migrations.RemoveField(
            model_name='ordercategory',
            name='parent',
        ),
        migrations.CreateModel(
            name='ProductionOrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.productionordercategory')),
            ],
            options={
                'ordering': ('code',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.productionordercategory'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.purchaseordercategory')),
            ],
            options={
                'ordering': ('code',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.purchaseordercategory'),
        ),
        migrations.CreateModel(
            name='SalesOrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.salesordercategory')),
            ],
            options={
                'ordering': ('code',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.salesordercategory'),
        ),
        migrations.AddConstraint(
            model_name='productionordercategory',
            constraint=models.UniqueConstraint(fields=('code', 'parent'), name='unique_production_order_category'),
        ),
        migrations.AddConstraint(
            model_name='productionordercategory',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent')), _negated=True), name='productionordercategory_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='purchaseordercategory',
            constraint=models.UniqueConstraint(fields=('code', 'parent'), name='unique_purchase_order_category'),
        ),
        migrations.AddConstraint(
            model_name='purchaseordercategory',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent')), _negated=True), name='purchaseordercategory_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='salesordercategory',
            constraint=models.UniqueConstraint(fields=('code', 'parent'), name='unique_sales_order_category'),
        ),
        migrations.AddConstraint(
            model_name='salesordercategory',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent')), _negated=True), name='salesordercategory_no_self_parent'),
        ),
        migrations.DeleteModel(
            name='OrderCategory',
        ),
    ]
