# Generated by Django 5.2.2 on 2025-09-14 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0069_remove_ordercategory_model_ct_and_more'),
        ('workflow', '0006_remove_state_allowed_groups_transitionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='workflow_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.state'),
        ),
    ]
