# Generated by Django 5.2.2 on 2025-09-14 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0070_receiptline_workflow_receiptline_workflow_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedorder',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='plannedorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='plannedorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='plannedorder',
            name='uom',
        ),
        migrations.CreateModel(
            name='PlannedProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=20, verbose_name='Planned Order')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Planned Quantity')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Planned Start Date')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Planned End Date')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Required Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.uom')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=20, verbose_name='Planned Order')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Planned Quantity')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Planned Start Date')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Planned End Date')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Required Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.item')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.businesspartner')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.uom')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionMrpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp_message', models.TextField(blank=True, default='', verbose_name='MRP Message')),
                ('mrp_reschedule_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='MRP Reschedule Date')),
                ('reschedule_delta_days', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Reschedule Delta Days')),
                ('direction', models.CharField(blank=True, choices=[('PULL_IN', 'Pull In'), ('PUSH_OUT', 'Push Out')], db_index=True, max_length=8, null=True, verbose_name='Reschedule Direction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='common.mrprescheduledaysclassification')),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_message', to='common.productionorder')),
            ],
            options={
                'ordering': ('-mrp_reschedule_date', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseMrpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp_message', models.TextField(blank=True, default='', verbose_name='MRP Message')),
                ('mrp_reschedule_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='MRP Reschedule Date')),
                ('reschedule_delta_days', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Reschedule Delta Days')),
                ('direction', models.CharField(blank=True, choices=[('PULL_IN', 'Pull In'), ('PUSH_OUT', 'Push Out')], db_index=True, max_length=8, null=True, verbose_name='Reschedule Direction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='common.mrprescheduledaysclassification')),
                ('pol', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_message', to='common.purchaseorderline')),
            ],
            options={
                'ordering': ('-mrp_reschedule_date', 'id'),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MrpMessage',
        ),
        migrations.DeleteModel(
            name='PlannedOrder',
        ),
        migrations.AddConstraint(
            model_name='plannedproductionorder',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_planned_production_order'),
        ),
        migrations.AddConstraint(
            model_name='plannedpurchaseorder',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_planned_purchase_order'),
        ),
    ]
