# Generated by Django 5.2.2 on 2025-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0073_itemgrouptype_program_itemgroup_sovalidateaggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Item Type Code')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Item Type Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_item_type')],
            },
        ),
    ]
