# Generated by Django 5.2.2 on 2025-09-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0074_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.itemgroup', verbose_name='Item Group'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.itemtype', verbose_name='Item Type'),
        ),
    ]
