# Generated by Django 5.2.2 on 2025-09-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0074_program_code_refactor'),
        ('common', '0075_item_item_group_item_type'),
    ]

    operations = [
    ]
