# Generated by Django 5.2.2 on 2025-09-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='WF State Name')),
                ('is_start', models.BooleanField(default=False, verbose_name='WF State Start')),
                ('is_end', models.BooleanField(default=False, verbose_name='WF State End')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Which user groups may trigger this', to='auth.group')),
                ('dest_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_to', to='workflow.state')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_from', to='workflow.state')),
            ],
        ),
        migrations.CreateModel(
            name='TransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('from_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.state')),
                ('to_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.state')),
                ('transition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.transition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='WF Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('inactive', 'Inactive')], default='active', help_text='“Active” allows creation & transitions; “Deprecated” allows transitions only; “Inactive” disallows both.', max_length=10, verbose_name='WF Status')),
                ('content_type', models.ForeignKey(blank=True, help_text='Which Django model this workflow is for', null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='WF Model')),
            ],
        ),
        migrations.AddField(
            model_name='transition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='workflow.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('workflow', 'source_state', 'dest_state', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('workflow', 'name')},
        ),
    ]
