# Generated by Django 5.2.2 on 2025-06-12 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_start', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Which groups may *edit* the document when it’s in this state.', null=True, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('obsolete', 'Obsolete'), ('inactive', 'Inactive')], default='active', help_text='“Active” allows creation & transitions; “Obsolete” allows transitions only; “Inactive” disallows both.', max_length=10)),
                ('content_type', models.ForeignKey(blank=True, help_text='Which Django model this workflow is for', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Which user groups may trigger this', to='auth.group')),
                ('dest_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='workflow.state')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='workflow.state')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflow')),
            ],
            options={
                'unique_together': {('workflow', 'source_state', 'dest_state', 'name')},
            },
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.transition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permlevel', models.PositiveSmallIntegerField(help_text='Matches the permlevel in FieldPermLevel')),
                ('actions', models.JSONField(default=list, help_text="List of allowed actions (e.g. ['read','write','add','change','delete','view'])")),
                ('content_type', models.ForeignKey(help_text='Which model this permission mapping applies to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(help_text='User group (role) this entry applies to', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'ordering': ('content_type', 'permlevel', 'group__name'),
                'unique_together': {('content_type', 'permlevel', 'group')},
            },
        ),
        migrations.CreateModel(
            name='FieldPermLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Name of the field (or '__model__' for model-level perms)", max_length=64)),
                ('permlevel', models.PositiveSmallIntegerField(blank=True, help_text='Numeric permission level (e.g. 1,2,3...)', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Which model this field belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('content_type', 'permlevel'),
                'unique_together': {('content_type', 'field_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('workflow', 'name')},
        ),
    ]
