# Generated by Django 5.2.2 on 2025-06-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_workflow_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldpermlevel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fieldpermlevel',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='FieldPermission',
        ),
        migrations.DeleteModel(
            name='FieldPermLevel',
        ),
    ]
