# Generated by Django 5.2.2 on 2025-06-27 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0003_alter_fieldpermlevel_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='dest_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_to', to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='source_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_from', to='workflow.state'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Which Django model this workflow is for', null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('inactive', 'Inactive')], default='active', help_text='“Active” allows creation & transitions; “Deprecated” allows transitions only; “Inactive” disallows both.', max_length=10),
        ),
        migrations.AlterField(
            model_name='workflowlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='workflowlog',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.transition'),
        ),
        migrations.AlterField(
            model_name='workflowlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
