# Generated by Django 5.2.2 on 2025-07-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0004_alter_state_workflow_alter_transition_dest_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Which groups may *edit* the document when it’s in this state.', null=True, to='auth.group', verbose_name='WF State Allowed Groups'),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='WF State End'),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_start',
            field=models.BooleanField(default=False, verbose_name='WF State Start'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, verbose_name='WF State Name'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Which Django model this workflow is for', null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='WF Model'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='WF Name'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('inactive', 'Inactive')], default='active', help_text='“Active” allows creation & transitions; “Deprecated” allows transitions only; “Inactive” disallows both.', max_length=10, verbose_name='WF Status'),
        ),
    ]
