# Generated by Django 5.2.2 on 2025-06-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableViewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('model_label', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tabulator_options', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
