# Generated by Django 5.2.2 on 2025-09-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('col', models.PositiveIntegerField(default=12)),
                ('col_sm', models.PositiveIntegerField(blank=True, null=True)),
                ('col_md', models.PositiveIntegerField(blank=True, null=True)),
                ('col_lg', models.PositiveIntegerField(blank=True, null=True)),
                ('col_xl', models.PositiveIntegerField(blank=True, null=True)),
                ('col_xxl', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('preferred_filter_name', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_column_config_name', models.CharField(blank=True, default='', max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.block')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='layout.layout')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LayoutFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('values', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_configs', to='layout.layout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='layout',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_layout_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='layout',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_layout_slug_per_user'),
        ),
        migrations.AddIndex(
            model_name='layoutblock',
            index=models.Index(fields=['layout', 'position'], name='layout_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('col__in', (1, 2, 3, 4, 6, 12))), name='layoutblock_col_allowed_values'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('col_sm__isnull', True), ('col_sm__in', (1, 2, 3, 4, 6, 12)), _connector='OR'), name='layoutblock_col_sm_allowed_values'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('col_md__isnull', True), ('col_md__in', (1, 2, 3, 4, 6, 12)), _connector='OR'), name='layoutblock_col_md_allowed_values'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('col_lg__isnull', True), ('col_lg__in', (1, 2, 3, 4, 6, 12)), _connector='OR'), name='layoutblock_col_lg_allowed_values'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('col_xl__isnull', True), ('col_xl__in', (1, 2, 3, 4, 6, 12)), _connector='OR'), name='layoutblock_col_xl_allowed_values'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('col_xxl__isnull', True), ('col_xxl__in', (1, 2, 3, 4, 6, 12)), _connector='OR'), name='layoutblock_col_xxl_allowed_values'),
        ),
        migrations.AddConstraint(
            model_name='layoutfilterconfig',
            constraint=models.UniqueConstraint(fields=('layout', 'user', 'name'), name='unique_layout_filter_per_user'),
        ),
        migrations.AddConstraint(
            model_name='layoutfilterconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('layout', 'user'), name='unique_default_layout_filter_per_user'),
        ),
    ]
