# Generated by Django 5.2.2 on 2025-06-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableviewconfig',
            name='is_default',
        ),
    ]
