# Generated by Django 5.2.2 on 2025-06-16 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_usercolumnconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercolumnconfig',
            unique_together={('user', 'table_config', 'name')},
        ),
    ]
