# Generated by Django 5.2.2 on 2025-06-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_alter_usercolumnconfig_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDisplayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=200)),
                ('field_name', models.CharField(max_length=100)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('model_label', 'field_name')},
            },
        ),
    ]
