# Generated by Django 5.2.2 on 2025-08-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_alter_block_name'),
        ('layout', '0005_remove_layoutblock_width_height'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='layoutblock',
            index=models.Index(fields=['layout', 'position'], name='layout_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='layoutblock',
            constraint=models.CheckConstraint(condition=models.Q(('col__in', (1, 2, 3, 4, 6, 12))), name='layoutblock_col_allowed_values'),
        ),
    ]
