# Generated by Django 5.2.2 on 2025-06-16 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_fielddisplayrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('values', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('table_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.tableviewconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'table_config', 'name')},
            },
        ),
    ]
