# Generated by Django 5.2.2 on 2025-06-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_userfilterconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tableviewconfig',
            unique_together={('table_name', 'model_label')},
        ),
    ]
