# Generated by Django 5.2.2 on 2025-06-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0007_alter_tableviewconfig_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableviewconfig',
            name='default_columns',
            field=models.JSONField(default=list, help_text='List of field-names, in order, to show by default'),
        ),
    ]
