# Generated by Django 5.2.2 on 2025-06-27 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0008_tableviewconfig_default_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercolumnconfig',
            name='table_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layout.tableviewconfig'),
        ),
        migrations.AlterField(
            model_name='usercolumnconfig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfilterconfig',
            name='table_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layout.tableviewconfig'),
        ),
        migrations.AlterField(
            model_name='userfilterconfig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
