# Generated by Django 5.2.2 on 2025-09-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0009_add_layout_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutfilterconfig',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=7),
        ),
    ]
