# Generated by Django 5.2.2 on 2025-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0010_layoutfilterconfig_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutblock',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
