# Generated by Django 5.2.2 on 2025-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0012_layout_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutblock',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='layoutblock',
            name='preferred_column_config_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layoutblock',
            name='preferred_filter_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layoutblock',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='layoutblock',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
